### ISSUE TITLE
Instagram Feed

### ISSUE THREAD

**Issue by tedleyem** [tedleyem/whovisionspresents.com#9]
This site needs a page that will share photos from Instagram in a grid-like fashion but not make it look like it's coming from Instagram.

**Comment by tedleyem** [comment]
Here is a link to the whovisions IG account 
https://www.instagram.com/whovisions

This should be a public account so scraping the data should be done with ease. I will look into adding keys to github to use for connecting to the account and getting more insight if thats needed.

**Comment by tedleyem** [comment]
I will add them to this repo that you will be able to get with github variables. 
I think a good example of this can be found in this link. 

https://stackoverflow.com/questions/62240661/embed-github-secret-in-react-and-deploy-to-github-page-revealed-my-personal-acce

**Comment by Sylar-codex** [comment]
I’ve started to work on project 1 though, structuring the layout and all of that.

**Comment by Sylar-codex** [comment]
When would the secret keys be available for me to use?

**Comment by tedleyem** [comment]
I dont know if the authentication token will help with just getting IG photos. It looks like the general usage is for sharing, posting, or using meta's messaging platform. If we could find a way to just scrape the images and share them on the page that would be ideal.

**Comment by Sylar-codex** [comment]
You can also get post I think, according to what the doc said, as soon as I took up this project, took some time to go through the documentation.

**Comment by tedleyem** [comment]
I am trying to spin up your branch using docker compose and get a failure in the build process. 
`
ERROR in [eslint] Failed to load plugin 'n' declared in '.eslintrc.js » eslint-config-standard': Unexpected token '?'`

are you able to build this project using docker-compose or test the changes in this branch?

**Comment by Sylar-codex** [comment]
Yes I did test it locally and ran into that same error, I had to delete package-lock.json. And ran npm install again.

**Comment by tedleyem** [comment]
I will test today.
